swagger: "2.0"
info:
  version: v1.0
  title: wgrest
  description: Manage WireGuard VPN tunnels by RESTful manner
securityDefinitions:
  key:
    type: apiKey
    in: header
    name: Token
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
  - https
paths:
  /devices/:
    post:
      summary: create new wireguard device
      operationId: DeviceCreate
      tags:
        - wireguard
      security:
        - key: []
      parameters:
        - name: device
          in: body
          description: device configuration
          required: true
          schema:
            $ref: "#/definitions/WireguardDevice"  
      responses:
        201:
          description: created
          headers:
            Location:
              type: string
        409:
          description: device exists
          schema:
            $ref: "#/definitions/Error"
        default:
          description: error
          schema:
            $ref: "#/definitions/Error"
      deprecated: false
    get:
      summary: get wireguard devices
      operationId: DeviceList
      tags:
        - wireguard
      security:
        - key: []
      responses:
        200:
          description: ok
          schema:
            type: array
            items:
              $ref: "#/definitions/WireguardDevice"
        default:
          description: error
          schema:
            $ref: "#/definitions/Error"
  /devices/{dev}:
    get:
      summary: get wireguard device details
      operationId: DeviceGet
      tags:
        - wireguard
      security:
        - key: []
      parameters:
        - name: dev
          in: path
          type: string
          required: true
      responses:
        200:
          description: ok
          schema:
            $ref: "#/definitions/WireguardDevice"
        404:
          description: not found
        default:
          description: error
          schema:
            $ref: "#/definitions/Error"
    delete:
      summary: delete wireguard interface
      operationId: DeviceDelete
      tags:
        - wireguard
      security:
        - key: []
      parameters:
        - name: dev
          in: path
          type: string
          required: true
      responses:
        204:
          description: no content
        404:
          description: not found
        default:
          description: error
          schema:
            $ref: "#/definitions/Error"
  /devices/{dev}/peers/:
    get:
      summary: get wireguard device's peers
      operationId: PeerList
      tags:
        - wireguard
      security:
        - key: []
      parameters:
        - name: dev
          in: path
          type: string
          required: true
      responses:
        200:
          description: ok
          schema:
            type: array
            items:
              $ref: "#/definitions/WireguardPeer"
        404:
          description: not found
        default:
          description: error
          schema:
            $ref: "#/definitions/Error"
    post:
      summary: add peer to wireguard device
      operationId: PeerCreate
      tags:
        - wireguard
      security:
        - key: []
      parameters:
        - name: dev
          in: path
          type: string
          required: true
        - name: peer
          in: body
          description: peer configuration
          required: true
          schema:
            $ref: "#/definitions/WireguardPeer"  
      responses:
        201:
          description: created
          headers:
            Location:
              type: string
        404:
          description: device not found
        default:
          description: error
          schema:
            $ref: "#/definitions/Error"
  /devices/{dev}/peers/{peer_id}:
    get:
      summary: wireguard peer's detail
      operationId: PeerGet
      tags:
        - wireguard
      security:
        - key: []
      parameters:
        - name: dev
          in: path
          type: string
          required: true
        - name: peer_id
          in: path
          type: string
          required: true
      responses:
        200:
          description: ok
          schema:
            $ref: "#/definitions/WireguardPeer"
        404:
          description: peer/device not found
        default:
          description: error
          schema:
            $ref: "#/definitions/Error"
    delete:
      summary: delete wireguard's peer
      operationId: PeerDelete
      tags:
        - wireguard
      security:
        - key: []
      parameters:
        - name: dev
          in: path
          type: string
          required: true
        - name: peer_id
          in: path
          type: string
          required: true
      responses:
        204:
          description: no content
        404:
          description: not found
        default:
          description: error
          schema:
            $ref: "#/definitions/Error"

definitions:
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int64
      detail:
        type: string
  WireguardDevice:
    type: object
    required:
      - name
      - listen_port
      - private_key
      - network
    properties:
      name: 
        type: string
      listen_port:
        type: integer
        format: int64
      public_key:
        type: string
        minLength: 32
        readOnly: true
      private_key:
        type: string
        minLength: 32
      network:
        type: string
  WireguardPeer:
    type: object
    required:
      - public_key
    properties:
      private_key:
        type: string
        minLength: 32
      public_key:
        type: string
        minLength: 32
      preshared_key:
        type: string
        minLength: 32
      end_point :
        type: string
      allowed_ips:
        type: array
        items:
          type: string
      peer_id:
        type: string
        readOnly: true
