// Code generated by go-swagger; DO NOT EDIT.

package wireguard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	"github.com/suquant/wgrest/models"
)

// DevicesCorsOKCode is the HTTP code returned for type DevicesCorsOK
const DevicesCorsOKCode int = 200

/*DevicesCorsOK ok

swagger:response devicesCorsOK
*/
type DevicesCorsOK struct {
	/*

	  Default: []interface {}{"GET", "POST"}
	*/
	AccessControlAllowMethods []string `json:"Access-Control-Allow-Methods"`
}

// NewDevicesCorsOK creates DevicesCorsOK with default headers values
func NewDevicesCorsOK() *DevicesCorsOK {

	var (
		// initialize headers with default values

		accessControlAllowMethodsDefault = []string{"GET", "POST"}
	)

	return &DevicesCorsOK{

		AccessControlAllowMethods: accessControlAllowMethodsDefault,
	}
}

// WithAccessControlAllowMethods adds the accessControlAllowMethods to the devices cors o k response
func (o *DevicesCorsOK) WithAccessControlAllowMethods(accessControlAllowMethods []string) *DevicesCorsOK {
	o.AccessControlAllowMethods = accessControlAllowMethods
	return o
}

// SetAccessControlAllowMethods sets the accessControlAllowMethods to the devices cors o k response
func (o *DevicesCorsOK) SetAccessControlAllowMethods(accessControlAllowMethods []string) {
	o.AccessControlAllowMethods = accessControlAllowMethods
}

// WriteResponse to the client
func (o *DevicesCorsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Access-Control-Allow-Methods

	var accessControlAllowMethodsIR []string
	for _, accessControlAllowMethodsI := range o.AccessControlAllowMethods {
		accessControlAllowMethodsIS := accessControlAllowMethodsI
		if accessControlAllowMethodsIS != "" {
			accessControlAllowMethodsIR = append(accessControlAllowMethodsIR, accessControlAllowMethodsIS)
		}
	}
	accessControlAllowMethods := swag.JoinByFormat(accessControlAllowMethodsIR, "")
	if len(accessControlAllowMethods) > 0 {
		hv := accessControlAllowMethods[0]
		if hv != "" {
			rw.Header().Set("Access-Control-Allow-Methods", hv)
		}
	}

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*DevicesCorsDefault error

swagger:response devicesCorsDefault
*/
type DevicesCorsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDevicesCorsDefault creates DevicesCorsDefault with default headers values
func NewDevicesCorsDefault(code int) *DevicesCorsDefault {
	if code <= 0 {
		code = 500
	}

	return &DevicesCorsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the devices cors default response
func (o *DevicesCorsDefault) WithStatusCode(code int) *DevicesCorsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the devices cors default response
func (o *DevicesCorsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the devices cors default response
func (o *DevicesCorsDefault) WithPayload(payload *models.Error) *DevicesCorsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the devices cors default response
func (o *DevicesCorsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DevicesCorsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
