// Code generated by go-swagger; DO NOT EDIT.

package wireguard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	"github.com/suquant/wgrest/models"
)

// DeviceCorsOKCode is the HTTP code returned for type DeviceCorsOK
const DeviceCorsOKCode int = 200

/*DeviceCorsOK ok

swagger:response deviceCorsOK
*/
type DeviceCorsOK struct {
	/*

	  Default: []interface {}{"GET", "DELETE"}
	*/
	AccessControlAllowMethods []string `json:"Access-Control-Allow-Methods"`
}

// NewDeviceCorsOK creates DeviceCorsOK with default headers values
func NewDeviceCorsOK() *DeviceCorsOK {

	var (
		// initialize headers with default values

		accessControlAllowMethodsDefault = []string{"GET", "DELETE"}
	)

	return &DeviceCorsOK{

		AccessControlAllowMethods: accessControlAllowMethodsDefault,
	}
}

// WithAccessControlAllowMethods adds the accessControlAllowMethods to the device cors o k response
func (o *DeviceCorsOK) WithAccessControlAllowMethods(accessControlAllowMethods []string) *DeviceCorsOK {
	o.AccessControlAllowMethods = accessControlAllowMethods
	return o
}

// SetAccessControlAllowMethods sets the accessControlAllowMethods to the device cors o k response
func (o *DeviceCorsOK) SetAccessControlAllowMethods(accessControlAllowMethods []string) {
	o.AccessControlAllowMethods = accessControlAllowMethods
}

// WriteResponse to the client
func (o *DeviceCorsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Access-Control-Allow-Methods

	var accessControlAllowMethodsIR []string
	for _, accessControlAllowMethodsI := range o.AccessControlAllowMethods {
		accessControlAllowMethodsIS := accessControlAllowMethodsI
		if accessControlAllowMethodsIS != "" {
			accessControlAllowMethodsIR = append(accessControlAllowMethodsIR, accessControlAllowMethodsIS)
		}
	}
	accessControlAllowMethods := swag.JoinByFormat(accessControlAllowMethodsIR, "")
	if len(accessControlAllowMethods) > 0 {
		hv := accessControlAllowMethods[0]
		if hv != "" {
			rw.Header().Set("Access-Control-Allow-Methods", hv)
		}
	}

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*DeviceCorsDefault error

swagger:response deviceCorsDefault
*/
type DeviceCorsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeviceCorsDefault creates DeviceCorsDefault with default headers values
func NewDeviceCorsDefault(code int) *DeviceCorsDefault {
	if code <= 0 {
		code = 500
	}

	return &DeviceCorsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the device cors default response
func (o *DeviceCorsDefault) WithStatusCode(code int) *DeviceCorsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the device cors default response
func (o *DeviceCorsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the device cors default response
func (o *DeviceCorsDefault) WithPayload(payload *models.Error) *DeviceCorsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the device cors default response
func (o *DeviceCorsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeviceCorsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
